name: Build and deploy
on: push
jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup 2 - Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Step 3 - gradle run
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
      - name: Command Runner
        run: |
          cd ./build/libs
          ls -R
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: my-artifact
          path: ./build/libs/*.jar